require("config.lazy")
require("config.bufferline")
require("config.comment")
require("config.noice")
require("config.whichkey")
require("config.nvim-tree")
require("config.telescope")
require("config.alpha")
require("config.treesitter")
require("config.lsp")
require("config.autopairs")
require("config.move")
require("config.lualine")

require("options")
require("keymaps")
